package com.patchr.objects;

public enum ActionType {
	ACTION_GET_ENTITY,
	ACTION_GET_ENTITIES,
	ACTION_GET_TREND,
	ACTION_GET_NOTIFICATIONS,
	ACTION_LINK_INSERT_LIKE,
	ACTION_LINK_DELETE_LIKE,
	ACTION_LINK_INSERT_MEMBER,
	ACTION_LINK_DELETE_MEMBER,
	ACTION_LINK_MUTE_WATCH,
	ACTION_ENTITY_INSERT,
	ACTION_SHARE_CHECK,
	ACTION_VIEW_CLICK
}
